[package]
name = "ico_math"
version = "0.1.0"
authors = ["Brian Kehrer <brian.kehrer@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "ico_math"
crate-type = ["staticlib", "cdylib"]

[profile.test]
opt-level = 3